function GARCHvol = garch_variance(theta, data)

% this function generate variance (volatility) sig^2 series usign the GARCH model

% Input: theta (omega, beta, alpha); data, a de-meaned time series data
% which can used as residuals

% Output: variance series generated by the GARCH model


[T,~] = size(data); % this is the number of observations

sig0 = var(data); % set the sample variance as the initial value

GARCHvol = [sig0; zeros(T-1,1)]; % create the vector for volatility series

for t = 2:T
    
    GARCHvol(t) = theta(1)+theta(2) * GARCHvol(t-1) + theta(3) * data(t)^2;
      
end

end